language: python
install:
- pip install tox-travis
- mkdir -p ~/bin
- |
  if [[ "$TRAVIS_PYTHON_VERSION" = "3.6" ]]
  then
    curl -L -o ~/bin/checkmate \
      https://github.com/spoqa/checkmate/releases/download/0.3.0/checkmate-linux-x86_64
    chmod +x ~/bin/checkmate
  fi
script:
- |
  [[ "$TRAVIS_PYTHON_VERSION" != "3.6" ]] || \
    ~/bin/checkmate github-travis --token "$GITHUB_ACCESS_TOKEN"
- tox
- tox -e mypy
python:
# CHECK If you're going to change the list of supported Python versions
# update tox.ini and setup.py's classifiers as well.
- pypy3.5
- 3.4
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
